[package]
name = "noir_psi_proof"       
type = "bin"
authors = ["cypriansakwa"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }

